### ISSUE TITLE
otto.de - cookie banners that are not being cleared

### ISSUE THREAD

**Issue by pdehaan** [mozilla/cookie-banner-rules-list#101]
via https://github.com/mozilla/Foxfooding_Cookie_Banner_Handling/issues/34

> **Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
> **Window Size (inner width and height):** 1280x955
> **GitHub Username:** @hokonch
> ## Steps to Reproduce
> 1) `cookiebanners.service.mode` set to `2`
> 2) Access `https://www.otto.de/`
>
> ## Expected Behavior
> All cookie banners are cleared as its domain covered on the list.
>
> ## Actual Behavior
> You notice a cookie banner that has not been cleared.
>
> ## Attachment
> ![Attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/38620307-fa08-4f1c-82f5-f0aafd1cde57.jpg)
> [Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/38620307-fa08-4f1c-82f5-f0aafd1cde57.jpg)

**Comment by Softvision-ValentinBandac** [comment]
I have verified that this issue is no longer reproducible using the latest v0.5.7 release on RS stage.
