### ISSUE TITLE
Cookie banners appeared on a few sites from the list

### ISSUE THREAD

**Issue by pdehaan** [mozilla/cookie-banner-rules-list#109]
Via foxfooding:

> On these sites cookie pop-ups/banners appeared:
> - bbc.com
> - cloudflare.com
> - ebay.de
> - flickr.com
> - serverfault.com
> - soundcloud.com
> - twitch.tv
> - weebly.com
>
> I tested those that I usually don't visit.

**Comment by Softvision-ValentinBandac** [comment]
I have verified that this issue is no longer reproducible using the latest V0.5.6 release on RS stage.
Opened issue #148 for bbc.com.
