### ISSUE TITLE
Cannot log in to instagram.com when the user selects to "Dismiss banners" from the "Cookie Banner" prompt

### ISSUE THREAD

**Issue by lobontiumira** [mozilla/cookie-banner-rules-list#173]
## Prerequisites
Have an instagram valid account.

## Steps to reproduce:
1. Open Firefox Nightly with a fresh profile.
2. Go to instagram.com.
3. The Cookie Banner Reduction prompt is displayed.
4. Select the "Dismiss banners".
5. Try to log in with valid credentials.

## Expected results
The user can log in without issues.

## Actual results
An error is displayed announcing the user the "CSRF token missing or incorrect".

![instagram](https://user-images.githubusercontent.com/40694158/218463742-c1d8521f-0ce8-4824-bb87-d804522a51e1.png)

## Environment:
* Fenix Nightly 111.0a1 from 2/13
* Devices: Oppo Find X3 Lite (Android 11), Google Pixel 6 (Android 13)
* NOT reproducible if the prompt is dismissed, and the cookie banner feature is enabled from Settings.

**Comment by Trikolon** [comment]
We should disable the rule for Mobile but keep it for Desktop until it's fixed.
