### ISSUE TITLE
Cookie banner not cleared on yahoo.com

### ISSUE THREAD

**Issue by rtestard** [mozilla/cookie-banner-rules-list#20]
Environment:
- MacOS
- Nightly 108
- cookiebanners.service.mode set to 2
- cookiebanners.service.mode.privateBrowsing set to 2

STR
- Browse to yahoo.com
- Observe the blurred UI without a cookie banner for 2 seconds
- The cookie banner appears

**Comment by jaredhirsch** [comment]
Interestingly, yahoo.com redirects to a consent page with a placeholder blurred image in the background. There actually isn't any content here, just a blurry image, so I don't think we should be hiding the banner element while it's handled. I'm not sure of the best way to handle this.

As a side note, the button selectors for reject all and accept all seem incorrect; I'll open a pull request to update those, but I don't think they will resolve this issue.
