### ISSUE TITLE
Add rule for arte.tv

### ISSUE THREAD

**Issue by arxo** [mozilla/cookie-banner-rules-list#211]
The site arte.tv uses trustcommander for its cookie banners.

Working click rule (haven't been able to figure out the "hide" part or cookies) :
`{
  "domains": ["arte.tv" ],
  "click": {
    "optIn": "#footer_tc_privacy_button",
    "optOut": "#footer_tc_privacy_button_2",
    "presence": ".tc-privacy-wrapper.tc-privacy-override.tc-privacy-wrapper"
  },
  "id": "arteViaTrustCommander"
}`

**Comment by Trikolon** [comment]
Thanks arxo! Would you like to create a PR that includes this change?

**Comment by arxo** [comment]
PR created

**Comment by Trikolon** [comment]
https://github.com/mozilla/cookie-banner-rules-list/commit/aa47adbe48e0a63b67997f3792bd4b2a504800a1
