### ISSUE TITLE
CBH opens comment section after load on theverge.com

### ISSUE THREAD

**Issue by Trikolon** [mozilla/cookie-banner-rules-list#214]
With the mechanism enabled when visiting an article on theverge.com the comment section expands on load.

Example: https://www.theverge.com/23802382/search-engine-google-neeva-android

We're probably targeting the wrong buttons here. The click selector may be too broad.

**Comment by saschanaz** [comment]
https://github.com/mozilla/cookie-banner-rules-list/blob/bb4ba7072106558baa7f448fba7eda1e4366f4e4/cookie-banner-rules-list.json#L5018-L5026

`button.text-blurple` is indeed too broad. It could be `div.duet--cta--cookie-banner > button.text-blurple`.
