### ISSUE TITLE
Broken rule on n-tv.de

### ISSUE THREAD

**Issue by rtestard** [mozilla/cookie-banner-rules-list#229]
I can see the banner 
<img width="842" alt="image" src="https://github.com/mozilla/cookie-banner-rules-list/assets/866979/6149bd28-8690-4957-beca-145a58cb507d">

**Comment by Trikolon** [comment]
No one click "reject" all option, but I'm currently checking if we can inject a cookie instead.

**Comment by Trikolon** [comment]
Found a way to get into PUR mode, but unfortunately none to handle the banner via cookie injection. It's a sourcepoint frame.
