### ISSUE TITLE
Broken rule on wetteronline.de

### ISSUE THREAD

**Issue by rtestard** [mozilla/cookie-banner-rules-list#231]
I can see the banner on <img width="1072" alt="image" src="https://github.com/mozilla/cookie-banner-rules-list/assets/866979/3b594c08-a236-4ff8-a722-99a6aade7886">

**Comment by Trikolon** [comment]
Same as wetteronline.de, we can only handle the banner in service mode 2 since it doesn't provide a "reject all" option.
