### ISSUE TITLE
cookie banner reduction breaks Gitlab

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/cookie-banner-rules-list#235]
https://about.gitlab.com/

The page cannot be scrolled with enabled cookie banner reduction.

**Comment by cadeyrn** [comment]
@Trikolon The cookie banner blocker no longer blocks the cookie banner on GitLab. The good news is that it also no longer breaks the website. Therefore I will close this issue.

**Comment by cadeyrn** [comment]
I don't know why I wasn't able to reproduce two days ago or if something changed with the latest rules deployment, but I can reproduce the site breakage again.

**Comment by Trikolon** [comment]
That's mostly https://bugzilla.mozilla.org/show_bug.cgi?id=1865148 combined with https://bugzilla.mozilla.org/show_bug.cgi?id=1865147 and not finding an opt-out option. Resolving these bugs will make failures less problematic. Additionally we can tweak the GitLab rule.

**Comment by Trikolon** [comment]
Fixed in https://github.com/mozilla/cookie-banner-rules-list/pull/278
