### ISSUE TITLE
cookie banner reduction breaks gHacks (Didomi)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/cookie-banner-rules-list#236]
https://www.ghacks.net/

The page cannot be scrolled with enabled cookie banner reduction. It uses Didomi as CMP.

**Comment by cadeyrn** [comment]
@Trikolon This is another candidate I would like to see to be fixed before the Germany rollout of the feature. Reasoning: Although it is an English-language website, it was founded in Germany, and I suspect that's one reason why the site is so popular in Germany. At least, I often see references to this site on German-speaking tech communities.

(And they regularly cite my articles as a source for Mozilla topics - so it is only fair that I stand up for this site. 😂)

**Comment by abhishekmadan30** [comment]
#274 fixes this, already opened a new issues to add the opt-out rule back
