### ISSUE TITLE
flickr rule hides the wrong element

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/cookie-banner-rules-list#24]
The flickr rule hides the cookie banner element (`.truste_box_overlay_inner`), but not the translucent dark overlay that sits beneath the cookie banner (`.truste_overlay`), so that the site looks odd.

With banner auto-hidden:

<img width="400" alt="Screenshot 2022-11-09 at 3 03 39 PM" src="https://user-images.githubusercontent.com/96396/200929944-acb3da31-4fc0-4ef4-a3e0-6c2ca3b4f9ee.png">

Correct appearance, with `div.truste_overlay` hidden as well as `div.truste_box_overlay_inner`:

<img width="400" alt="Screenshot 2022-11-09 at 3 05 06 PM" src="https://user-images.githubusercontent.com/96396/200930203-2cf523ec-15cf-4709-9d81-ed3c3913dd6e.png">

Note that the DOM structure requires us to hide two sibling elements whose parent element is the body el:
```
<body>
  ... lots of stuff ...
  <div class="truste_overlay"></div>
  <div class="truste_box_overlay">
    <div class="truste_box_overlay_inner">
```

I wonder if it might make sense to target the `truste_box_overlay` instead of `truste_box_overlay_inner`.

**Comment by jaredhirsch** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1800908 to pick up the hiding multiple nodes discussion in BMO

**Comment by Softvision-ValentinBandac** [comment]
I have verified that this issue is no longer reproducible using the latest V0.5.6 release on RS stage.
