### ISSUE TITLE
missing rule for Sky and DWDL

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/cookie-banner-rules-list#249]
https://www.sky.de and https://www.sky.at still show a cookie banner with enabled cookie reduction.

**Comment by cadeyrn** [comment]
Seems to be a CMP, https://www.dwdl.de/ loads the consent script from the same domain (cdn.privacy-mgmt.com) but I don't know which CMP this is.

**Comment by abhishekmadan30** [comment]
Banners get dismissed

**Comment by cadeyrn** [comment]
@abhishekmadan30 This is not fixed. Can it be reopened?
