### ISSUE TITLE
Computerbase.de and Golem.de

### ISSUE THREAD

**Issue by CalvinSchwartz** [mozilla/cookie-banner-rules-list#287]
For [golem.de](golem.de) and [computerbase.de](computerbase.de) currently (Firefox 120.0) there is no autoselection of the "accept/confirm and continue" - "Akzeptieren/Zustimmen und weiter" button.

Missing Rule

**Comment by reinerh** [comment]
Submitted computerbase.de in #296.

**Comment by scharmach** [comment]
Added golem.de in #319.
