### ISSUE TITLE
https://arduinogetstarted.com/ is broken

### ISSUE THREAD

**Issue by simon-friedberger** [mozilla/cookie-banner-rules-list#433]
Context: `cookiebanners.service.mode = 2`

The banner show. 
Clicking "Manage Settings" on the banner makes the banner disappear and doesn't show the settings the site remains darkened and blurred.
Clicking on "Continue with Recommended Cookies" works.

**Comment by Trikolon** [comment]
Talked to Simon, this seems to not be related to cookie banner handling directly, as it also breaks when the feature is disabled. It's either a webcompat issue or a general issue with the website.
