### ISSUE TITLE
Cookie rule for n-tv.de not working

### ISSUE THREAD

**Issue by Trikolon** [mozilla/cookie-banner-rules-list#45]
When I disable banner clicking by setting `cookiebanners.bannerClicking.enabled` to `false` and visit https://n-tv.de the cookie banner still shows up. This is probably because the cookie we set is dynamically generated and not replayable. We can rely solely on the clicking instead.

This cookie might not replayable generally. We should check all cases where we inject cookies with the key `euconsent-v2`.

**Comment by Softvision-ValentinBandac** [comment]
I have verified that this issue is no longer reproducible using the latest V0.5.6 release on RS stage.
