### ISSUE TITLE
About.instagram.com is an unsupported website

### ISSUE THREAD

**Issue by Greg-21** [mozilla/cookie-banner-rules-list#499]
About.instagram.com displays a cookie banner (see the attached screenshot below) when visiting it for the first time or after clearing cookies in your browser. As there is currently no site-specific rule on how to handle this banner, nor does any global rule know how to deal with it either, this is fully understandable and expected.

However, it appears that the selectors used in the existing rule for the standard cookie banner used by Meta on a large part of their websites should also work for the banner on about.instagram.com, so adding support for it would be rather straightforward. ~~IF the Firefox cookie banner blocker could handle subdomains. But it cannot, so this is currently blocked on [bug 1789455](https://bugzilla.mozilla.org/show_bug.cgi?id=1789455) (on Bugzilla), which needs to be resolved first before we can proceed here.~~

EDIT: After a brief conversation with Trikolon, I came to the conclusion that about.instagram.com can just pretend to be instagram.com and immediately benefit from automatic banner handling even without support for subdomains in the Firefox cookie banner blocker. At least for now, until someone figures out how to deal with the "proper" Instagram banner and wants to add a rule for it, which will require revisiting the idea of adding subdomain support ([bug 1789455](https://bugzilla.mozilla.org/show_bug.cgi?id=1789455) on Bugzilla) and separating the instagram.com and about.instagram.com domains.

![Cookie-banner-on-about-instagram-com](https://github.com/mozilla/cookie-banner-rules-list/assets/34160838/1f2dae81-0075-4687-a6e3-3953d02ee507)

**Comment by Trikolon** [comment]
@Greg-21 while the mechanism doesn't support subdomain-specific rules, it should still run the rule for instagram.com. Can you check why that doesn't work?

**Comment by Trikolon** [comment]
Oh I just saw #498 ... we don't support Instagram currently. We couldn't come up with good, stable query selectors for the banner elements.

**Comment by Greg-21** [comment]
Trikolon, would it be an acceptable solution to add instagram.com to the same rule that already handles the standard cookie banner used by Meta on their other websites, such as facebook.com, messenger.com, oculus.com, etc., so that at least this banner on about.instagram.com is supported?

It should do the trick until someone figures out how to deal with the "proper" Instagram banner and wants to add a rule for it, which will require revisiting the idea of adding subdomain support and separating the instagram.com and about.instagram.com domains.

**Comment by Trikolon** [comment]
Yes, that seems acceptable as long as we don't break anything on instagram.com.
