### ISSUE TITLE
www.is.fi is broken in some cases when using Nightly in pb mode

### ISSUE THREAD

**Issue by smaug----** [mozilla/cookie-banner-rules-list#513]
is.fi is a popular yellow press site which every now and then embeds x or instagram. Using Nightly in pb mode seems to prevent showing the cookie banner, and without that the embedded pages aren't loaded.

**Comment by Trikolon** [comment]
Likely not an issue with cookie banner handling itself but with ETP blocking the resources of the cookie banner:
![image](https://github.com/mozilla/cookie-banner-rules-list/assets/1077860/e4ab38d8-b53f-4a37-ba71-da287969e34d)

Moving to https://bugzilla.mozilla.org/show_bug.cgi?id=1898043
