### ISSUE TITLE
skype.com not handled

### ISSUE THREAD

**Issue by pdehaan** [mozilla/cookie-banner-rules-list#72]
via https://github.com/mozilla/Foxfooding_Cookie_Banner_Handling/issues/3

> **Firefox Version:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0
> **Window Size (inner width and height):** 1868x1088
> **GitHub Username:** @127001
> ## Steps to Reproduce
> Open https://skype.com
>
> ## Expected Behavior
> The top cookie banner to be denied.
> 
> ## Actual Behavior
> Cookiebanner remains visible.
> 
> ## Attachment
> ![Attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/5e36b6b7-83c6-4672-9fc8-602c6dd63f2d.png)
[Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/5e36b6b7-83c6-4672-9fc8-602c6dd63f2d.png)

**Comment by Softvision-ValentinBandac** [comment]
I have verified that this issue is no longer reproducible using the latest V0.5.6 release on RS stage.
