### ISSUE TITLE
businessinsider.com.pl - site breakage - unscrollable

### ISSUE THREAD

**Issue by pdehaan** [mozilla/cookie-banner-rules-list#77]
via https://github.com/mozilla/Foxfooding_Cookie_Banner_Handling/issues/10

> **Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
> **Window Size (inner width and height):** 1280x955
> **GitHub Username:** @hokonch
> ## Steps to Reproduce
> 1) cookiebanners.service.mode set to 2
> 2) Access https://businessinsider.com.pl/
>
> ## Expected Behavior
> Scrollable
>
> ## Actual Behavior
> Unscrollable
>
> ## Attachment
> ![Attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/50f2e89c-1613-40be-a375-0e0c2323c2b3.png)
> [Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/50f2e89c-1613-40be-a375-0e0c2323c2b3.png)

**Comment by Softvision-ValentinBandac** [comment]
I have verified that this issue is no longer reproducible using the latest V0.5.3 release on RS prod.
