### ISSUE TITLE
dhl.de - site breakage - infinite reload

### ISSUE THREAD

**Issue by pdehaan** [mozilla/cookie-banner-rules-list#78]
via https://github.com/mozilla/Foxfooding_Cookie_Banner_Handling/issues/11

> **Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
> **Window Size (inner width and height):** 1280x955
> ## Steps to Reproduce
> 1) Set `cookiebanners.service.mode` to 2
> 2) Access https://www.dhl.de/de/privatkunden.html
>
> ## Expected Behavior
> Loading finished successfully
> 
> ## Actual Behavior
> Infinite reload

**Comment by Trikolon** [comment]
Fixed by #106
