### ISSUE TITLE
wetteronline.de - site breakage - unscrollable

### ISSUE THREAD

**Issue by pdehaan** [mozilla/cookie-banner-rules-list#88]
via https://github.com/mozilla/Foxfooding_Cookie_Banner_Handling/issues/21

> **Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
> **Window Size (inner width and height):** 1280x955
> **GitHub Username:** @hokonch
> ## Steps to Reproduce
> 1) `cookiebanners.service.mode` set to `2`
> 2) Access `https://www.wetteronline.de/`
>
> ## Expected Behavior
> scrollable
>
> ## Actual Behavior
> unscrollable
>
> ## Attachment
> ![Attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/173ace16-5f44-475f-8d40-4d16dbf4cf97.png)
> [Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/173ace16-5f44-475f-8d40-4d16dbf4cf97.png)

**Comment by Softvision-ValentinBandac** [comment]
I have verified that this issue is no longer reproducible using the latest V0.5.3 release on RS stage.
