### ISSUE TITLE
20minutes.fr - cookie banners that are not being cleared

### ISSUE THREAD

**Issue by pdehaan** [mozilla/cookie-banner-rules-list#89]
Via https://github.com/mozilla/Foxfooding_Cookie_Banner_Handling/issues/22

> **Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
> **Window Size (inner width and height):** 1280x955
> **GitHub Username:** @hokonch
> ## Steps to Reproduce
> 1) `cookiebanners.service.mode` set to `2`
> 2) Access `https://www.20minutes.fr/`
>
> ## Expected Behavior
> All cookie banners are cleared.
>
> ## Actual Behavior
> You notice a cookie banner that has not been cleared
>
> ## Attachment
> ![Attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/0ae3a917-73ec-4c22-9536-f7a4b03da6f1.jpg)
> [Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/0ae3a917-73ec-4c22-9536-f7a4b03da6f1.jpg)

**Comment by Softvision-ValentinBandac** [comment]
I have verified that this issue is no longer reproducible using the latest V0.5.3 release on RS stage.
