### ISSUE TITLE
actu.fr - cookie banners that are not being cleared

### ISSUE THREAD

**Issue by pdehaan** [mozilla/cookie-banner-rules-list#91]
via https://github.com/mozilla/Foxfooding_Cookie_Banner_Handling/issues/24

> **Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
> **Window Size (inner width and height):** 1280x955
> **GitHub Username:** @hokonch
> ## Steps to Reproduce
> 1) `cookiebanners.service.mode` set to `2`
> 2) Access `https://actu.fr/`
>
> ## Expected Behavior
> All cookie banners are cleared as it is a supported site.
>
> ## Actual Behavior
> You notice a cookie banner that has not been cleared.
>
> ## Attachment
> ![Attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/e84e0273-1bf5-4379-92b1-5ff085a1073d.jpg)
> [Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/e84e0273-1bf5-4379-92b1-5ff085a1073d.jpg)

**Comment by Softvision-ValentinBandac** [comment]
I have verified that this issue is no longer reproducible using the latest V0.5.3 release on RS stage.
